import React, { useState } from 'react';
import { 
  Briefcase, 
  PlusCircle, 
  DollarSign, 
  Eye, 
  CheckCircle2, 
  XCircle, 
  AlertTriangle, 
  ExternalLink, 
  Layers, 
  Play, 
  TrendingUp,
  Clock,
  ShieldCheck,
  Video
} from 'lucide-react';
import confetti from 'canvas-confetti';

export default function BrandView({ 
  campaigns, 
  submissions, 
  onApproveSubmission, 
  onRejectSubmission, 
  openCreateModal,
  platformFee 
}) {
  const [activeTab, setActiveTab] = useState('review-queue'); // 'review-queue' | 'my-campaigns'

  // Pending Submissions
  const pendingSubmissions = submissions.filter(s => s.status === 'Pending');
  const approvedSubmissions = submissions.filter(s => s.status === 'Approved' || s.status === 'Paid');

  // Aggregated Brand Stats
  const totalEscrowBudget = campaigns.reduce((acc, c) => acc + c.totalBudget, 0);
  const totalSpentBudget = campaigns.reduce((acc, c) => acc + c.spentBudget, 0);
  const totalBrandViews = campaigns.reduce((acc, c) => acc + c.totalViews, 0);

  const handleApprove = (submission) => {
    confetti({
      particleCount: 50,
      spread: 60,
      origin: { y: 0.7 }
    });
    onApproveSubmission(submission.id);
  };

  return (
    <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '2rem 1.5rem' }}>
      
      {/* Brand Dashboard Stats Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '1.2rem', marginBottom: '2rem' }}>
        
        <div className="glass-panel" style={{ padding: '1.5rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.8rem' }}>
            <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: '600', textTransform: 'uppercase' }}>Escrow Vault Budget</span>
            <DollarSign size={18} color="var(--accent-purple)" />
          </div>
          <div style={{ fontSize: '1.8rem', fontWeight: '800', color: '#fff' }}>
            ${(totalEscrowBudget - totalSpentBudget).toLocaleString()}
          </div>
          <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
            of ${totalEscrowBudget.toLocaleString()} total deposited
          </span>
        </div>

        <div className="glass-panel" style={{ padding: '1.5rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.8rem' }}>
            <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: '600', textTransform: 'uppercase' }}>Spent on Payouts</span>
            <TrendingUp size={18} color="var(--accent-emerald)" />
          </div>
          <div style={{ fontSize: '1.8rem', fontWeight: '800', color: 'var(--accent-emerald)' }}>
            ${totalSpentBudget.toLocaleString()}
          </div>
          <span style={{ fontSize: '0.75rem', color: '#34d399' }}>
            Released to Clippers
          </span>
        </div>

        <div className="glass-panel" style={{ padding: '1.5rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.8rem' }}>
            <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: '600', textTransform: 'uppercase' }}>Total Organic Views</span>
            <Eye size={18} color="var(--accent-cyan)" />
          </div>
          <div style={{ fontSize: '1.8rem', fontWeight: '800', color: 'var(--accent-cyan)' }}>
            {(totalBrandViews / 1000000).toFixed(2)}M
          </div>
          <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
            Generated by Clippers
          </span>
        </div>

        <div className="glass-panel" style={{ padding: '1.5rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.8rem' }}>
            <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontWeight: '600', textTransform: 'uppercase' }}>Pending Review</span>
            <Clock size={18} color="var(--accent-amber)" />
          </div>
          <div style={{ fontSize: '1.8rem', fontWeight: '800', color: 'var(--accent-amber)' }}>
            {pendingSubmissions.length} clips
          </div>
          <span style={{ fontSize: '0.75rem', color: '#fbbf24' }}>
            Awaiting Approval
          </span>
        </div>

      </div>

      {/* Main Container */}
      <div className="glass-panel" style={{ padding: '2rem' }}>
        
        {/* Header Bar */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '1rem' }}>
          <div style={{ display: 'flex', gap: '0.5rem', background: 'rgba(255,255,255,0.03)', padding: '0.3rem', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-subtle)' }}>
            <button 
              onClick={() => setActiveTab('review-queue')}
              style={{
                padding: '0.6rem 1.2rem',
                borderRadius: 'var(--radius-sm)',
                border: 'none',
                cursor: 'pointer',
                fontWeight: '600',
                fontSize: '0.88rem',
                background: activeTab === 'review-queue' ? 'var(--accent-primary)' : 'transparent',
                color: activeTab === 'review-queue' ? '#fff' : 'var(--text-muted)',
                display: 'flex',
                alignItems: 'center',
                gap: '0.5rem'
              }}
            >
              <span>Submissions Queue</span>
              {pendingSubmissions.length > 0 && (
                <span className="badge badge-amber">{pendingSubmissions.length} pending</span>
              )}
            </button>

            <button 
              onClick={() => setActiveTab('my-campaigns')}
              style={{
                padding: '0.6rem 1.2rem',
                borderRadius: 'var(--radius-sm)',
                border: 'none',
                cursor: 'pointer',
                fontWeight: '600',
                fontSize: '0.88rem',
                background: activeTab === 'my-campaigns' ? 'var(--accent-primary)' : 'transparent',
                color: activeTab === 'my-campaigns' ? '#fff' : 'var(--text-muted)'
              }}
            >
              Active Campaigns ({campaigns.length})
            </button>
          </div>

          <button className="btn-primary" onClick={openCreateModal}>
            <PlusCircle size={16} /> Create Campaign
          </button>
        </div>

        {/* TAB 1: SUBMISSIONS REVIEW QUEUE */}
        {activeTab === 'review-queue' && (
          <div>
            {submissions.length === 0 ? (
              <div style={{ padding: '3rem', textAlign: 'center', color: 'var(--text-muted)' }}>
                <p>No clip submissions yet. Clippers will submit their links here once they post!</p>
              </div>
            ) : (
              <div style={{ overflowX: 'auto' }}>
                <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', fontSize: '0.9rem' }}>
                  <thead>
                    <tr style={{ borderBottom: '1px solid var(--border-subtle)', color: 'var(--text-muted)', fontSize: '0.78rem', textTransform: 'uppercase' }}>
                      <th style={{ padding: '1rem' }}>Clipper</th>
                      <th style={{ padding: '1rem' }}>Campaign</th>
                      <th style={{ padding: '1rem' }}>Submitted Video</th>
                      <th style={{ padding: '1rem' }}>Views</th>
                      <th style={{ padding: '1rem' }}>Payout Total</th>
                      <th style={{ padding: '1rem' }}>Status</th>
                      <th style={{ padding: '1rem', textAlign: 'right' }}>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {submissions.map(s => (
                      <tr key={s.id} style={{ borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
                        <td style={{ padding: '1rem' }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
                            <img src={s.clipperAvatar} alt="" style={{ width: '34px', height: '34px', borderRadius: '50%', objectFit: 'cover' }} />
                            <div>
                              <div style={{ fontWeight: '600', color: '#fff' }}>{s.clipperHandle}</div>
                              <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>{s.submittedAt}</span>
                            </div>
                          </div>
                        </td>

                        <td style={{ padding: '1rem', color: 'var(--text-muted)', fontSize: '0.85rem' }}>
                          {s.campaignTitle}
                        </td>

                        <td style={{ padding: '1rem' }}>
                          <a href={s.videoUrl} target="_blank" rel="noreferrer" style={{ color: 'var(--accent-cyan)', textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: '0.3rem', fontWeight: '600' }}>
                            <Video size={14} /> Open Video <ExternalLink size={12} />
                          </a>
                        </td>

                        <td style={{ padding: '1rem', fontFamily: 'var(--font-mono)', fontWeight: '700' }}>
                          {s.views.toLocaleString()} views
                        </td>

                        <td style={{ padding: '1rem', fontFamily: 'var(--font-mono)', fontWeight: '800', color: 'var(--accent-emerald)' }}>
                          ${s.grossPayout.toFixed(2)}
                          <span style={{ display: 'block', fontSize: '0.7rem', color: 'var(--text-muted)', fontWeight: '400' }}>
                            (${s.netPayout.toFixed(2)} net to clipper)
                          </span>
                        </td>

                        <td style={{ padding: '1rem' }}>
                          {s.status === 'Pending' && <span className="badge badge-amber"><Clock size={12} /> Pending</span>}
                          {s.status === 'Approved' && <span className="badge badge-cyan"><CheckCircle2 size={12} /> Approved</span>}
                          {s.status === 'Paid' && <span className="badge badge-emerald"><CheckCircle2 size={12} /> Paid Out</span>}
                          {s.status === 'Rejected' && <span className="badge badge-rose">Rejected</span>}
                        </td>

                        <td style={{ padding: '1rem', textAlign: 'right' }}>
                          {s.status === 'Pending' ? (
                            <div style={{ display: 'inline-flex', gap: '0.5rem' }}>
                              <button 
                                className="btn-emerald" 
                                style={{ padding: '0.4rem 0.8rem', fontSize: '0.8rem' }}
                                onClick={() => handleApprove(s)}
                              >
                                <CheckCircle2 size={14} /> Approve & Pay
                              </button>
                              <button 
                                className="btn-secondary" 
                                style={{ padding: '0.4rem 0.8rem', fontSize: '0.8rem', color: '#fb7185' }}
                                onClick={() => onRejectSubmission(s.id)}
                              >
                                <XCircle size={14} /> Reject
                              </button>
                            </div>
                          ) : (
                            <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Action Completed</span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        )}

        {/* TAB 2: ACTIVE CAMPAIGN MANAGEMENT */}
        {activeTab === 'my-campaigns' && (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(350px, 1fr))', gap: '1.5rem' }}>
            {campaigns.map(c => (
              <div key={c.id} style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-md)', padding: '1.5rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1rem' }}>
                  <div>
                    <h3 style={{ fontSize: '1.1rem', fontWeight: '700', color: '#fff' }}>{c.title}</h3>
                    <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{c.platform} • {c.category}</span>
                  </div>
                  <span className="badge badge-emerald">{c.status}</span>
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.8rem', margin: '1rem 0', background: 'rgba(0,0,0,0.2)', padding: '0.8rem', borderRadius: '8px' }}>
                  <div>
                    <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>Payout Rate</span>
                    <div style={{ fontWeight: '700', color: 'var(--accent-cyan)' }}>${c.payoutPer1k.toFixed(2)} / 1k</div>
                  </div>
                  <div>
                    <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>Budget Spent</span>
                    <div style={{ fontWeight: '700', color: 'var(--accent-emerald)' }}>${c.spentBudget} / ${c.totalBudget}</div>
                  </div>
                </div>

                <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '1rem' }}>
                  Total Generated Views: <strong style={{ color: '#fff' }}>{(c.totalViews / 1000).toFixed(0)}k views</strong>
                </div>

                <button className="btn-secondary" style={{ width: '100%', justifyContent: 'center' }} onClick={openCreateModal}>
                  Edit Campaign Settings
                </button>
              </div>
            ))}
          </div>
        )}

      </div>

    </div>
  );
}
